[resume.render]
personal = true
education = true
certifications = true
experience = true

[resume.render.section.personal]
contact_info = true
banner = true
visa_status = true
websites = true
note = true
name = true
email = true
phone = true
location = true
linkedin = true
github = true
website = true
twitter = true
require_sponsorship = true
work_authorization = true

[resume.render.section.experience.section.projects]
overview = true
description = true
skills = true
title = true
url = true
url_description = true
start_date = true
end_date = true

[resume.render.section.experience.section.roles]
summary = true
skills = true
responsibilities = true
reason_for_change = true
location = true
job_category = true
employment_type = true
agency_name = true
start_date = true
end_date = true

[resume.render.section.experience.section.functional]
# disable these by setting them to "" or omit them entirely

categories = """
Category1
Category2
"""

skills = """
Skill1
Skill2
"""

[resume.render.section.certifications]
name = true
issuer = true
issued = true
expires = true

[resume.render.section.education]
degrees = true
school = true
degree = true
start_date = true
end_date = true
gpa = true
major = true
