[resume.render]
personal = true
education = false
certifications = false

[resume.render.section.personal]
visa_status = false
note = false

[resume.render.section.certifications]
issuer = false
issued = false
expires = false

[resume.render.section.experience.section.roles]
summary = false