[resume.render]
personal = true
education = false
certifications = true

[resume.render.section.personal]
visa_status = false
note = false

[resume.render.section.certifications]
issuer = false
issued = false
expires = false

[resume.render.section.experience.section.roles]
summary = true

[resume.render.section.experience.section.functional]
# disable these by setting them to "" or omit them entirely
categories = """
Architecture
Development
DevOps
"""

skills = """
Python
AWS
Docker
Kubernetes
Terraform
Ansible
JavaScript
NIST
CI/CD
Security (general)
SQL (general)
Team lead
"""