[resume.render]
personal = true
education = false
certifications = false


[resume.render.section.personal]
visa_status = false
note = false

[resume.render.section.certifications]
name = true
issuer = false
issued = false
expires = false