[resume.render]
personal = true
education = true
certifications = true
experience = true
executive_summary = true
skills_matrix = true

font_size = 10
margin_width = 0.5
top_margin = 0.2
bottom_margin = 0.2


[resume.render.section.personal]
contact_info = true
banner = true
visa_status = true
websites = true
note = true
name = true
email = true
phone = true
location = true
linkedin = true
github = true
website = true
twitter = true
require_sponsorship = true
work_authorization = true

[resume.render.section.experience]
roles = true
projects = true

[resume.render.section.experience.section.projects]
overview = true
description = true
skills = true
title = true
url = true
url_description = true
start_date = true
end_date = true

[resume.render.section.experience.section.roles]
summary = true
skills = true
responsibilities = true
reason_for_change = true
location = true
job_category = true
employment_type = true
agency_name = true
start_date = true
end_date = true
months_ago = 0
include_tasks = true
include_situation = true

[resume.render.section.executive_summary]
# Categories are displayed in this order
categories = """
Worker
"""

[resume.render.section.skills_matrix]
skills = """
Skill 1
Skill 2
"""

[resume.render.section.certifications]
name = true
issuer = true
issued = true
expires = true
certification_id = true

[resume.render.section.education]
degrees = true
school = true
degree = true
start_date = true
end_date = true
gpa = true
major = true
